production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: static_secret_key

test:
  secret_key_base: static_test_secret_key


#not_indented: key for all env in once
secret_key_base: 3b7cd727ee24e8444053437c36cc66c3
